### ISSUE TITLE
想要知道元素移动过程中找线的逻辑，想知道这部分逻辑的源码在哪里

### ISSUE THREAD

**Issue by yohuu** [qq15725/yh5#1]
您好，我在[知乎上](https://zhuanlan.zhihu.com/p/92469406)看到您的这个项目，想请教下元素移动过程中是怎么找线的。
比如一个元素移动时发现跟另一个元素中线对齐了，这时候要显示一条对齐的线。请问您是怎么判断该跟哪个元素对齐，怎么判断他们对齐了，以及怎么把线渲染出来。
所以能帮忙指出来这部分逻辑是在源码的哪一部分吗？我找了很长时间找不到。

**Comment by qq15725** [comment]
计算参考线数据

https://github.com/qq15725/yh5/blob/bb3e05057e27e7585b92056751020ac1f68153e9/packages/yh5/src/components/VSketch/VSketch.js#L431

生成参考线 vnode

https://github.com/qq15725/yh5/blob/bb3e05057e27e7585b92056751020ac1f68153e9/packages/yh5/src/components/VSketch/VSketch.js#L344

具体渲染的地方

https://github.com/qq15725/yh5/blob/bb3e05057e27e7585b92056751020ac1f68153e9/packages/yh5/src/components/VCanvas/VCanvas.js#L161
